export type SkillScriptLanguage = "javascript" | "python" | "csharp";

type SkillScriptRule = {
  id: string;
  reason: string;
  pattern: RegExp;
  languages?: SkillScriptLanguage[];
};

export type SkillScriptScanResult = {
  safe: boolean;
  reasons: string[];
  matchedRuleIds: string[];
};

const harmfulRules: SkillScriptRule[] = [
  { id: "js-eval", reason: "Dynamic code execution is not allowed.", pattern: /\b(eval|Function)\s*\(/i, languages: ["javascript"] },
  { id: "js-child-process", reason: "Spawning system processes is blocked.", pattern: /\b(child_process|spawn|execFile|execSync)\b/i, languages: ["javascript"] },
  { id: "js-filesystem", reason: "Direct filesystem mutation is blocked.", pattern: /\b(require\s*\(\s*["']fs["']|fs\.(rm|unlink|rmdir|writeFile|appendFile|createWriteStream))\b/i, languages: ["javascript"] },
  { id: "js-secret-access", reason: "Reading server environment secrets is blocked.", pattern: /\bprocess\.env\b/i, languages: ["javascript"] },
  { id: "python-eval-exec", reason: "Python dynamic execution is not allowed.", pattern: /\b(eval|exec|compile)\s*\(/i, languages: ["python"] },
  { id: "python-system-process", reason: "Python system command execution is blocked.", pattern: /\b(os\.system|subprocess\.|pty\.spawn)\b/i, languages: ["python"] },
  { id: "python-destructive-fs", reason: "Destructive Python filesystem operations are blocked.", pattern: /\b(shutil\.rmtree|os\.remove|os\.unlink|Path\(.+\)\.unlink|open\s*\(\s*["']\/etc\/passwd)/i, languages: ["python"] },
  { id: "python-socket", reason: "Raw socket access is blocked for marketplace skills.", pattern: /\b(socket\.socket|import\s+socket)\b/i, languages: ["python"] },
  { id: "csharp-process", reason: "C# process launching is blocked.", pattern: /\b(Process\.Start|System\.Diagnostics\.Process)\b/i, languages: ["csharp"] },
  { id: "csharp-destructive-fs", reason: "Destructive C# filesystem operations are blocked.", pattern: /\b(File\.Delete|Directory\.Delete|File\.WriteAll|FileStream)\b/i, languages: ["csharp"] },
  { id: "csharp-reflection", reason: "Reflection and dynamic assembly loading are blocked.", pattern: /\b(Assembly\.Load|Activator\.CreateInstance|Type\.GetType)\b/i, languages: ["csharp"] },
  { id: "shell-download-exec", reason: "Download-and-execute shell patterns are blocked.", pattern: /\b(curl|wget|Invoke-WebRequest|iwr)\b.+(\|\s*(bash|sh|powershell|pwsh)|-OutFile\s+\S+\s*;)/i },
  { id: "shell-destructive", reason: "Destructive shell commands are blocked.", pattern: /\b(rm\s+-rf|del\s+\/[fsq]|Remove-Item\s+.+-Recurse|format\s+[a-z]:|chmod\s+777)\b/i },
  { id: "metadata-service", reason: "Cloud metadata service access is blocked.", pattern: /\b(169\.254\.169\.254|metadata\.google\.internal|169\.254\.170\.2)\b/i },
  { id: "credential-exfiltration", reason: "Credential exfiltration patterns are blocked.", pattern: /\b(document\.cookie|localStorage|sessionStorage|Authorization\s*[:=]|Bearer\s+\$\{|password\s*[:=].+fetch)\b/i },
  { id: "encoded-payload", reason: "Encoded payload execution is blocked.", pattern: /\b(atob|fromBase64|Convert\.FromBase64String|base64\.b64decode)\b.+\b(eval|exec|Assembly\.Load|Function)\b/i },
  { id: "ai-generated-marker", reason: "Explicit AI-generated code markers are not allowed in custom skill submissions.", pattern: /\b(generated by chatgpt|as an ai language model|ai-generated|copilot generated|this code was generated by|generated with ai)\b/i },
];

export function scanSkillScript(code: string, language: SkillScriptLanguage): SkillScriptScanResult {
  const trimmed = code.trim();
  if (!trimmed) {
    return {
      safe: false,
      reasons: ["A custom skill needs an implementation script before it can be added."],
      matchedRuleIds: ["empty-script"],
    };
  }

  const matches = harmfulRules.filter((rule) => (!rule.languages || rule.languages.includes(language)) && rule.pattern.test(trimmed));
  return {
    safe: matches.length === 0,
    reasons: [...new Set(matches.map((rule) => rule.reason))],
    matchedRuleIds: matches.map((rule) => rule.id),
  };
}
